theme: jekyll-theme-minimal
title: "DATALENTS"
description: "Somos una empresa de consultoria organizacional centrada en la gestión del talento humano y el análisis de datos organizacional."
logo: https://github.com/daneira66/Datalents/blob/master/Logo.png
